title: Default page

sections:
  contents:
    type: fields
    fields:
      text:
        label: Text
        extends: fields/writer-basic

  seo_fields:
    type: fields
    fields:
      seo_description:
        label: Descrizione SEO
        type: textarea
        rows: 3
