title: Prodotto

columns:
  - width: 1/2
    sections:
      intro_fields:
        type: fields
        fields:
          tech_drawing:
            label: Disegno tecnico
            type: files
            max: 1
            accepts:
              mime: image/*

          intro_text:
            extends: fields/writer-basic

          blocks:
            label: Blocks
            type: blocks
            fieldsets:
              - text-block
              - 3-col-text-block
              - img-block

  - width: 1/2
    sections:

      tech_sheet:
        type: fields
        label: Dati tecnici
        fields:
          cover_img:
            label: Immagine di anteprima
            type: files
            max: 1
            accepts:
              mime: image/*

          design:
            label: Design
            type: text
            help: 'Se presente verrà mostrato nella pagina dei Prodotti.'

          measures:
            label: Misure
            type: text
            width: 1/2

          weight:
            label: Peso
            type: text
            width: 1/2

          finishing:
            label: Finitura
            type: text
            help: 'Se presente avrà priorità sui tre campi sotto.'

          finishing_front:
            label: Finitura fronte
            type: text
            width: 1/3

          finishing_back:
            label: Finitura retro
            type: text
            width: 1/3

          coste:
            label: Coste
            type: text
            width: 1/3

          variables:
            label: Colori
            type: structure
            columns:
              title:
                width: 1/1
            fields:
              title:
                label: Titolo
                type: text
              image:
                label: Immagine
                type: files
                max: 1
                accepts:
                  mime: image/*
              text:
                label: Breve testo
                type: textarea
                rows: 3

      download_section:
        type: fields
        label: Download
        fields:
          pdf:
            label: Scheda PDF
            type: files
            max: 1
            accepts:
              mime: application/pdf




